spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-id: ${AZURE_CLIENT_ID}
          client-secret: ${AZURE_CLIENT_SECRET}
        profile:
          tenant-id: ${AZURE_TENANT_ID}
        post-logout-redirect-uri: http://localhost:8080
        authorization-clients:
          azure:
            scopes: https://graph.microsoft.com/User.Read
        user-group:
          allowed-group-names: group_name_1, group_name_2
