azure:
  activedirectory:
    application-type: resource_server
    app-id-uri: ${APP_ID_URI}
    tenant-id: ${AZURE_TENANT_ID}
    client-id: ${AZURE_CLIENT_ID}
    client-secret: ${AZURE_CLIENT_SECRET}
    user-group:
      allowed-group-names: group_name_1, group_name_2