azure:
  activedirectory:
    application-type: web_application_and_resource_server
    app-id-uri: ${APP_ID_URI}
    tenant-id: ${AZURE_TENANT_ID}
    client-id: ${AZURE_CLIENT_ID}
    client-secret: ${AZURE_CLIENT_SECRET}
    authorization-clients:
      azure:
        authorization-grant-type: authorization_code
        scopes: https://graph.microsoft.com/User.Read